Adjust github process variables

diff --git a/.github/workflows/packaging-openwrt.yml b/.github/workflows/packaging-openwrt.yml
--- a/.github/workflows/packaging-openwrt.yml
+++ b/.github/workflows/packaging-openwrt.yml
@@ -60,7 +60,7 @@ env:
 jobs:
   build:
     runs-on: ubuntu-22.04
-    if: github.event.repository.owner.id == github.event.sender.id
+    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
 
     steps:
       - name: Checkout
@@ -77,10 +77,11 @@ jobs:
           sudo -E apt-get -qq autoremove --purge
           sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "${TZ}"
-          echo "::set-output name=status::success"
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Download armvirt file
         id: download
+        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
           # Custom repository and Releases keywords for *rootfs.tar.gz file
           armvirt_rootfsfile_repo="ophub/amlogic-s9xxx-openwrt"
@@ -96,12 +97,12 @@ jobs:
           #
           # Download the *rootfs.tar.gz file to the specified directory
           wget -q -P "${save_rootfsfile_path}" "https://github.com/${armvirt_rootfsfile_repo}/releases/download/${openwrt_url}"
-          [[ "${?}" -ne "0" ]] && echo "The armvirt file download failed!" && exit 1
-          echo "::set-output name=status::success"
+          [[ "${?}" -ne "0" ]] && echo -e "The armvirt file download failed!" && exit 1
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Package OpenWrt Firmware
         uses: ophub/flippy-openwrt-actions@main
-        if: steps.download.outputs.status == 'success' && !cancelled()
+        if: ${{ steps.download.outputs.status }} == 'success' && !cancelled()
         env:
           OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
           PACKAGE_SOC: ${{ github.event.inputs.openwrt_soc }}
@@ -110,7 +111,7 @@ jobs:
 
       - name: Upload OpenWrt Firmware to Release
         uses: ncipollo/release-action@main
-        if: env.PACKAGED_STATUS == 'success' && !cancelled()
+        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
         with:
           tag: OpenWrt_aarch64_${{ env.PACKAGED_OUTPUTDATE }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
