Add long-term storage option

diff --git a/.github/workflows/packaging-openwrt.yml b/.github/workflows/packaging-openwrt.yml
--- a/.github/workflows/packaging-openwrt.yml
+++ b/.github/workflows/packaging-openwrt.yml
@@ -71,6 +71,14 @@ on:
         description: "Set custom script loading path"
         required: false
         default: ""
+      openwrt_storage:
+        description: "Select OpenWrt image storage time."
+        required: false
+        default: "lts"
+        type: choice
+        options:
+          - lts
+          - tmp
 
 env:
   TZ: America/New_York
@@ -106,26 +114,32 @@ jobs:
         id: download
         if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
-          # Custom repository and Releases keywords for *rootfs.tar.gz file
-          armvirt_rootfsfile_repo="ophub/amlogic-s9xxx-openwrt"
-          releases_tag_keywords="OpenWrt_.*lede.*/.*rootfs.tar.gz"
+          armvirt_tarfile_repo="ophub/amlogic-s9xxx-openwrt"
+          releases_tag_keywords="OpenWrt_lede"
 
-          # The following download paths, etc. can remain unchanged
-          save_rootfsfile_path="openwrt/bin/targets/armvirt/64"
-          [[ -d "${save_rootfsfile_path}" ]] || mkdir -p ${save_rootfsfile_path}
+          armvirt_tarfile_path="openwrt/bin/targets/armvirt/64"
+          [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}
 
-          # Get the *rootfs.tar.gz file download address
-          openwrt_url="$(curl \
-                            --header "authorization: Bearer ${{ secrets.GH_TOKEN }}" \
-                            -s "https://api.github.com/repos/${armvirt_rootfsfile_repo}/releases" |
-                            grep -oE "${releases_tag_keywords}" | head -n 1
-                        )"
-          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
-          down_file="https://github.com/${armvirt_rootfsfile_repo}/releases/download/${openwrt_url}"
+          latest_version="$(curl -s \
+                              -H "Accept: application/vnd.github+json" \
+                              -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
+                              https://api.github.com/repos/${armvirt_tarfile_repo}/releases |
+                              jq '.[]' |
+                              jq -s --arg RTK "${releases_tag_keywords}" '.[] | select(.tag_name | contains($RTK))' |
+                              jq -s '.[].assets[] | {data:.updated_at, url:.browser_download_url}' |
+                              jq -s --arg BOARD "-rootfs.tar.gz" '.[] | select(.url | endswith($BOARD))' |
+                              jq -s 'sort_by(.data)|reverse[]' |
+                              jq -s '.[0]' -c
+                          )"
 
-          # Download the *rootfs.tar.gz file to the specified directory
-          wget -q -P "${save_rootfsfile_path}" "${down_file}"
-          [[ "${?}" -ne "0" ]] && echo -e "The armvirt file download failed!" && exit 1
+          [[ "${latest_version}" == "null" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
+          latest_updated_at="$(echo ${latest_version} | jq -r '.data')"
+          latest_url="$(echo ${latest_version} | jq -r '.url')"
+
+          wget -q -P "${armvirt_tarfile_path}" "${latest_url}"
+          [[ "${?}" -ne "0" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
+
+          echo "build_tag=${releases_tag_keywords}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
           echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Package OpenWrt Firmware
@@ -144,13 +158,16 @@ jobs:
         uses: ncipollo/release-action@main
         if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
         with:
-          tag: OpenWrt_aarch64_${{ env.PACKAGED_OUTPUTDATE }}
+          tag: ${{ steps.download.outputs.build_tag }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
+          removeArtifacts: false
+          replacesArtifacts: true
           token: ${{ secrets.GH_TOKEN }}
           body: |
             This is OpenWrt firmware for Armvirt 64
             * Firmware information
+            OpenWrt Image Verification: sha256sum
             Default IP: 192.168.1.1
             Default username: root
             Default password: password
